FROM ubuntu

RUN apt-get update \
    && export DEBIAN_FRONTEND=noninteractive \
    && apt-get install -y software-properties-common \
    && add-apt-repository --yes ppa:jonathonf/gcc-9.0 \
    && apt-get install -y g++-9 \
    && apt-get install -y libopencv-dev \
    && apt-get install -y libboost-all-dev \
    && apt-get install -y wget \
    && apt-get install -y unzip \
    && apt-get install -y cmake \
    && apt-get install -y python3.7-dev \
    && apt-get install -y libgtest-dev \
    && cd /usr/src/gtest && cmake . && make install \
    && mkdir ~/anaconda && cd ~/anaconda && wget https://repo.anaconda.com/archive/Anaconda3-2019.10-Linux-x86_64.sh \
    && /bin/bash Anaconda3-2019.10-Linux-x86_64.sh -b -p "/opt/conda" && export PATH="$PATH:/opt/conda/bin" \
    && conda init \
    && /opt/conda/bin/python -m pip install opencv-python \
    && /opt/conda/bin/python -m pip install jsonschema \
    && /opt/conda/bin/python -m pip install requests \
    && mkdir ~/libs && cd ~/libs \
    && wget https://download.pytorch.org/libtorch/cpu/libtorch-cxx11-abi-shared-with-deps-1.3.1%2Bcpu.zip \
    && unzip libtorch-cxx11-abi-shared-with-deps-1.3.1+cpu.zip  \
    && rm -rf libtorch-cxx11-abi-shared-with-deps-1.3.1+cpu.zip \
    && rm -rf ~/anaconda/Anaconda3-2019.10-Linux-x86_64.sh

ENV PATH="${PATH}:/opt/conda/bin:/opt/conda/lib/python3.7/site-packages"
ENV Torch_DIR="~/libs/libtorch/share/cmake"

RUN mkdir ~/ImageClassifier && cd ~/ImageClassifier \
    && wget https://github.com/dz1domin/bachelors/archive/master.zip \
    && unzip master.zip && cd bachelors-master \
    && pytest && /opt/conda/bin/python ~/ImageClassifier/bachelors-master/CNN/test/run_tests.py \
    && /opt/conda/bin/python ~/ImageClassifier/bachelors-master/CNN/build.py
    
RUN cd ~/ImageClassifier/bachelors-master/ScrapperScript \
    && echo '13474752-7f4d5ee19e3fdf0354dae6977\nyellow+flower' | /opt/conda/bin/python ScrapperScript.py \
    && cd ~/ImageClassifier/bachelors-master/PrepareSamples \
    && /opt/conda/bin/python PrepareSamples.py

WORKDIR /root/ImageClassifier/bachelors-master
ENTRYPOINT echo "Classification has been started \n\
check logs.txt for details" && /bin/bash run_all_classifications.sh > logs.txt
